### ISSUE TITLE
Is this for ICS3U or ICS4U?

### ISSUE THREAD

**Issue by fffelix-jan** [NutmegCat/Sieve-of-Eratosthenes#4]
Hi, it's Felix, I hope you still remember me :)

Is this for ICS3U or ICS4U out of curiosity?

Good luck with your programming studies!

**Comment by NutmegCat** [comment]
Hey Felix,

Currenlty it's for ICS3U. Wasnt super hard thankfully

Thanks for reaching out. Best wishes in uni
